/// <reference types="react" />
import * as React from "react";
import { IAllContractsProps } from "./IAllContractsProps";
import "@pnp/polyfill-ie11";
import "moment/locale/zh-cn";
import { IAllContractsState } from "./IAllContractsState";
export default class AllContracts extends React.Component<IAllContractsProps, IAllContractsState> {
    private ContractTypes;
    private ContractStatus;
    private ContractMainBodies;
    private ContractTitle;
    private ContractNo;
    private ContractCurrencies;
    private MinMoneyInput;
    private MaxMoneyInput;
    private RelativePartyinput;
    private ContractDepts;
    constructor(props: any);
    render(): React.ReactElement<IAllContractsProps>;
    private _onRenderItemColumn(item, index, column);
    private _ItemInvoked(item?, index?, ev?);
    componentDidMount(): void;
    private colNames;
    private colKeys;
    getDatas(): void;
    private _formatDate(datevale);
    getFilterStr(CallBack: Function): void;
    Search(): void;
    exportDatas(): void;
    _exportDatas(): void;
    private onContractTypeChanged(e);
    private onRelativePartyChanged(e);
    private onContractDeptChanged(e);
    private onContractStatuChanged(e);
    private onContractMainBodyChanged(e);
    private onContractTitleChanged(e);
    private onContractNoChanged(e);
    private onContractCurrencyChanged(e);
    private setMinMoney(e);
    private setMaxMoney(e);
    private _setMinDate(value);
    private _setMaxDate(value);
    private onAuthorChanged(authors?);
    private _pagedItemsTo(PgItems, targetPage, PgNum);
    private _pagedItemsToExcel(PgItems, expItems, attfinfos);
    private _fillreqdata(req, page);
    private fillDatas(items, expItems, attfinfos);
    private _getpageditems(page);
}
